MyCritics/Models/Avaliacao.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MyCritics.Models {
    public class Avaliacao {
        public int ID { get; set; }
        public Usuario Usuario { get; set; }
        public int UsuarioID { get; set; }
        public Filme Filme { get; set; }
        public int FilmeID { get; set; }
        public int NotaFilme { get; set; }
        public int NotaDiretor { get; set; }
        public int NotaFigurino { get; set; }
        public int NotaRoteiro { get; set; }
        public int NotaSonoplastia { get; set; }
        public string Comentario { get; set; }

        public Avaliacao() {
        }

        public Avaliacao(int iD, int usuario, int filme, int notaFilme, int notaDiretor, int notaFigurino, int notaRoteiro, int notaSonoplastia) {
            ID = iD;
            UsuarioID = usuario;
            FilmeID = filme;
            NotaFilme = notaFilme;
            NotaDiretor = notaDiretor;
            NotaFigurino = notaFigurino;
            NotaRoteiro = notaRoteiro;
            NotaSonoplastia = notaSonoplastia;
        }
    }
}

MyCritics/Controllers/AvaliacaosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MyCritics.Data;
using MyCritics.Models;

namespace MyCritics.Controllers {
    public class AvaliacaosController : Controller {
        private readonly MyCriticsContext _context;

        public AvaliacaosController(MyCriticsContext context) {
            _context = context;
        }

        // GET: Avaliacaos1
        public async Task<IActionResult> Index() {
            var myCriticsContext = _context.Avaliacao.Include(a => a.Filme).Include(a => a.Usuario);
            return View(await myCriticsContext.ToListAsync());
        }

        // GET: Avaliacaos1/Details/5
        public async Task<IActionResult> Details(int? id) {
            if (id == null) {
                return NotFound();
            }

            var avaliacao = await _context.Avaliacao
                .Include(a => a.Filme)
                .Include(a => a.Usuario)
                .FirstOrDefaultAsync(m => m.ID == id);
            if (avaliacao == null) {
                return NotFound();
            }

            return View(avaliacao);
        }

        // GET: Avaliacaos1/Create
        public IActionResult Create(Filme filme) {
            var filmenome = _context.Filme.Where(m => m.ID.Equals(filme.ID)).FirstOrDefault();
            TempData["Filme"] = filmenome.Nome;
            TempData["FilmeID"] = filmenome.ID;
            TempData["FilmeDescricao"] = filmenome.Descricao;
            return View();
        }

        // POST: Avaliacaos1/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("UsuarioID,FilmeID,NotaFilme,NotaDiretor,NotaFigurino,NotaRoteiro,NotaSonoplastia,Comentario")] Avaliacao avaliacao) {
            if (ModelState.IsValid) {
                await _context.AddAsync(avaliacao);
                await _context.SaveChangesAsync();
                return RedirectToAction("Indicacoes", "Home");
            }
            return View(avaliacao);
        }

        // GET: Avaliacaos1/Edit/5
        public async Task<IActionResult> Edit(int? id) {
            if (id == null) {
                return NotFound();
            }

            var avaliacao = await _context.Avaliacao.FindAsync(id);
            if (avaliacao == null) {
                return NotFound();
            }
            ViewData["FilmeID"] = new SelectList(_context.Filme, "ID", "ID", avaliacao.FilmeID);
            ViewData["UsuarioID"] = new SelectList(_context.Usuario, "ID", "ID", avaliacao.UsuarioID);
            return View(avaliacao);
        }

        // POST: Avaliacaos1/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,UsuarioID,FilmeID,NotaFilme,NotaDiretor,NotaFigurino,NotaRoteiro,NotaSonoplastia,Comentario")] Avaliacao avaliacao) {
            if (id != avaliacao.ID) {
                return NotFound();
            }

            if (ModelState.IsValid) {
                try {
                    _context.Update(avaliacao);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException) {
                    if (!AvaliacaoExists(avaliacao.ID)) {
                        return NotFound();
                    }
                    else {
                        throw;
                    }
                }
                return RedirectToAction("Perfil","Home");
            }
            ViewData["FilmeID"] = new SelectList(_context.Filme, "ID", "ID", avaliacao.FilmeID);
            ViewData["UsuarioID"] = new SelectList(_context.Usuario, "ID", "ID", avaliacao.UsuarioID);
            return View(avaliacao);
        }

        // GET: Avaliacaos1/Delete/5
        public async Task<IActionResult> Delete(int? id) {
            if (id == null) {
                return NotFound();
            }

            var avaliacao = await _context.Avaliacao
                .Include(a => a.Filme)
                .Include(a => a.Usuario)
                .FirstOrDefaultAsync(m => m.ID == id);
            if (avaliacao == null) {
                return NotFound();
            }

            return View(avaliacao);
        }

        // POST: Avaliacaos1/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id) {
            var avaliacao = await _context.Avaliacao.FindAsync(id);
            _context.Avaliacao.Remove(avaliacao);
            await _context.SaveChangesAsync();
            return RedirectToAction("Perfil","Home");
        }

        private bool AvaliacaoExists(int id) {
            return _context.Avaliacao.Any(e => e.ID == id);
        }
    }
}

MyCritics/Controllers/FilmesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MyCritics.Data;
using MyCritics.Models;

namespace MyCritics.Controllers
{
    public class FilmesController : Controller
    {
        private readonly MyCriticsContext _context;

        public FilmesController(MyCriticsContext context)
        {
            _context = context;
        }

        // GET: Filmes
        public async Task<IActionResult> Index()
        {
            return View(await _context.Filme.ToListAsync());
        }

        // GET: Filmes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var filme = await _context.Filme
                .FirstOrDefaultAsync(m => m.ID == id);
            if (filme == null)
            {
                return NotFound();
            }

            return View(filme);
        }

        // GET: Filmes/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Filmes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,Nome,Descricao,Ano")] Filme filme)
        {
            if (ModelState.IsValid)
            {
                _context.Add(filme);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(filme);
        }

        // GET: Filmes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var filme = await _context.Filme.FindAsync(id);
            if (filme == null)
            {
                return NotFound();
            }
            return View(filme);
        }

        // POST: Filmes/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,Nome,Descricao,Ano")] Filme filme)
        {
            if (id != filme.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(filme);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!FilmeExists(filme.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(filme);
        }

        // GET: Filmes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var filme = await _context.Filme
                .FirstOrDefaultAsync(m => m.ID == id);
            if (filme == null)
            {
                return NotFound();
            }

            return View(filme);
        }

        // POST: Filmes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var filme = await _context.Filme.FindAsync(id);
            _context.Filme.Remove(filme);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool FilmeExists(int id)
        {
            return _context.Filme.Any(e => e.ID == id);
        }
    }
}

MyCritics/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MyCritics.Data;
using MyCritics.Models;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace MyCritics.Controllers {
    public class HomeController : Controller {

        private readonly MyCriticsContext _context;

        public HomeController(MyCriticsContext context) {
            _context = context;
        }

        public Usuario Sessao(Usuario usuario) {

            var login = _context.Usuario.Where(a => a.Email.Equals(usuario.Email)).FirstOrDefault();

            return login;

        }


        public IActionResult Login() {

            return View();
        }

        [HttpPost]
        public IActionResult Login(Usuario usuario) {


            if (Sessao(usuario).Password == usuario.Password) {
                TempData["Nome"] = Sessao(usuario).Nome;
                TempData["Sobrenome"] = Sessao(usuario).Sobrenome;
                TempData["ID"] = Sessao(usuario).ID;
                return View("Inicial", _context.Avaliacao.Include(a => a.Filme));
            }
            else {

                return View();
            }

        }

        public IActionResult Pesquisa() {
            return View();
        }
        public IActionResult Avaliacao() {
            return View();
        }
        public async Task<IActionResult> Perfil() {
            var myCriticsContext = _context.Avaliacao.Include(a => a.Filme).Include(a => a.Usuario).Where(m=>m.UsuarioID.Equals(TempData.Peek("ID")));
            return View(await myCriticsContext.ToListAsync());
        }

            public async Task<IActionResult> Indicacoes() {
            return View(await _context.Filme.ToListAsync());
        }

        public IActionResult Inicial() {
             ;
            return View(_context.Avaliacao.Include(a => a.Filme));
        }


            [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error() {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MyCritics/Controllers/UsuariosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MyCritics.Data;
using MyCritics.Models;
using System.IO;
using Microsoft.AspNetCore.Http;

namespace MyCritics.Controllers {
    public class UsuariosController : Controller {
        private readonly MyCriticsContext _context;

        public UsuariosController(MyCriticsContext context) {
            _context = context;
        }

        // GET: Usuarios
        public async Task<IActionResult> Index() {
            return View(await _context.Usuario.ToListAsync());
        }

        // GET: Usuarios/Details/5
        public async Task<IActionResult> Details(int? id) {
            if (id == null) {
                return NotFound();
            }

            var usuario = await _context.Usuario
                .FirstOrDefaultAsync(m => m.ID == id);
            if (usuario == null) {
                return NotFound();
            }

            return View(usuario);
        }

        // GET: Usuarios/Create
        public IActionResult Create() {
            return View();
        }

        // POST: Usuarios/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Usuario usuario) {

            if (ModelState.IsValid) {
                _context.Add(usuario);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(usuario);
        }

        // GET: Usuarios/Edit/5
        public async Task<IActionResult> Edit(int? id) {
            if (id == null) {
                return NotFound();
            }

            var usuario = await _context.Usuario.FindAsync(id);
            if (usuario == null) {
                return NotFound();
            }
            return View(usuario);
        }

        // POST: Usuarios/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,Password,Nome,Sobrenome,Email,Cidade,Estado,DataNascimento,file")] Usuario usuario) {
            if (id != usuario.ID) {
                return NotFound();
            }

            if (ModelState.IsValid) {
                try {
                    _context.Update(usuario);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException) {
                    if (!UsuarioExists(usuario.ID)) {
                        return NotFound();
                    }
                    else {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(usuario);
        }

        // GET: Usuarios/Delete/5
        public async Task<IActionResult> Delete(int? id) {
            if (id == null) {
                return NotFound();
            }

            var usuario = await _context.Usuario
                .FirstOrDefaultAsync(m => m.ID == id);
            if (usuario == null) {
                return NotFound();
            }

            return View(usuario);
        }

        // POST: Usuarios/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id) {
            var usuario = await _context.Usuario.FindAsync(id);
            _context.Usuario.Remove(usuario);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool UsuarioExists(int id) {
            return _context.Usuario.Any(e => e.ID == id);
        }
    }
}

MyCritics/Views/Home/Avaliacao.cshtml
<body>
    <div class="cabecalho" id="cab_login_registrar">
        <div class="logoNome">
            <a href="">
                <img src="~/images/abacate-removebg-preview.png" alt="some text" width=50 height=51>
            </a>
            <a class="cabecalho__botao-nav" asp-action="Inicial" asp-controller="Home">MY CRITICS</a>
        </div>
        <a class="cabecalho__botao-nav" asp-controller="home" asp-action="Indicacoes">
            <p class="p"> Lista de Filmes </p>
        </a>
        <a class="cabecalho__botao-nav" asp-controller="Filmes" asp-action="Create">
            <p class="p"> Cadastrar Filme </p>
        </a>
        <div class="">
            <p></p>
            <a asp-controller="home" asp-action="Perfil">
                <img src="~/images/mulher-perfil.jpg" alt="some text" width=51 height=52 class="Pesquisa">
                <p class="Titulo"> Clara </p>
            </a>

            <p></p>
        </div>
    </div>
    <div class="Principal">
        <div class="conteudo-avaliacao">
            <div class="filmes-pesquisados">
                <div class="filme">
                    <div class="imagem">
                        <img src="~/images/avengers.jpg" alt="some text" width=100% height=100%>
                    </div>
                    <div>
                        <p>Avengers</p>
                        <p>Earth's mightiest heroes must come together and learn to fight as a team if they are going to stop the mischievous Loki and his alien army from enslaving humanity.</p>
                    </div>
                </div>
            </div>
            <div class="titulo">
                <p>Sua Avaliação</p>
            </div>
            <div class="container">
                <div class="tabela">
                    <p>Categorias</p>
                    <div class="abacatokens">
                        <img src="~/images/abacate-removebg-preview.png" alt="some text" width=33 height=34>
                        <img src="~/images/abacate-removebg-preview.png" alt="some text" width=33 height=34>
                        <img src="~/images/abacate-removebg-preview.png" alt="some text" width=33 height=34>
                        <img src="~/images/abacate-removebg-preview.png" alt="some text" width=33 height=34>
                        <img src="~/images/abacate-removebg-preview.png" alt="some text" width=33 height=34>
                    </div>
                    <p>Filme</p>
                    <div class="abacatokens">
                        <input type="checkbox"></input>
                        <input type="checkbox"></input>
                        <input type="checkbox"></input>
                        <input type="checkbox"></input>
                        <input type="checkbox"></input>
                    </div>
                    <p>Direção</p>
                    <div class="abacatokens">
                        <input type="checkbox"></input>
                        <input type="checkbox"></input>
                        <input type="checkbox"></input>
                        <input type="checkbox"></input>
                        <input type="checkbox"></input>
                    </div>

                    <p>Roteiro</p>
                    <div class="abacatokens">
                        <input type="checkbox"></input>
                        <input type="checkbox"></input>
                        <input type="checkbox"></input>
                        <input type="checkbox"></input>
                        <input type="checkbox"></input>
                    </div>
                    <p>Sonoplastia</p>
                    <div class="abacatokens">
                        <input type="checkbox"></input>
                        <input type="checkbox"></input>
                        <input type="checkbox"></input>
                        <input type="checkbox"></input>
                        <input type="checkbox"></input>
                    </div>
                    <p>Figurino</p>
                    <div class="abacatokens">
                        <input type="checkbox"></input>
                        <input type="checkbox"></input>
                        <input type="checkbox"></input>
                        <input type="checkbox"></input>
                        <input type="checkbox"></input>
                    </div>

                    <div class="label_comentarios">
                        <p>Comentários:</p>
                    </div>
                    <div class="comentarios">
                        <textarea name="Text1" cols="40" rows="10"></textarea>
                    </div>
                    <p></p>
                    <div class="justifica">
                        <button class="botao">Enviar</button>
                    </div>

                </div>
            </div>
        </div>
    </div>
</body>

MyCritics/Views/Home/Indicacoes.cshtml
@model IEnumerable<MyCritics.Models.Filme>
<body>

    <div class="cabecalho" id="cab_login_registrar">
        <div class="logoNome">
            <a href="">
                <img src="~/images/abacate-removebg-preview.png" alt="some text" width=50 height=51>
            </a>
            <a class="cabecalho__botao-nav" asp-action="Inicial" asp-controller="Home">MY CRITICS</a>
        </div>
        <a class="cabecalho__botao-nav" asp-controller="Filmes" asp-action="Create">
            <p class="p"> Cadastrar Filme </p>
        </a>
        <div class="">
            <p></p>
            <a asp-controller="home" asp-action="Perfil">
                <p class="Titulo"> @TempData.Peek("Nome") </p>
            </a>

            <p></p>
        </div>
    </div>
    <div class="Principal">
        <p class="formulario__titulo">FILMES CADASTRADOS</p>
        
        <div class="">
            <hr />
            <table class="table">
                <thead>
                    <tr class="indicacoes__tr">
                        <th class="indicacoes__td">
                            @Html.DisplayNameFor(model => model.Nome)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Descricao)
                        </th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td class="indicacoes__td">
                                @Html.DisplayFor(modelItem => item.Nome)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Descricao)
                            </td>
                            <td class="indicacoes__td__btn">
                                <a asp-controller="Avaliacaos" asp-action="Create" asp-route-id="@item.ID">Avaliar</a>

                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</body>

MyCritics/Views/Home/Inicial.cshtml
@model IEnumerable<MyCritics.Models.Avaliacao>
<body>

    <div class="cabecalho" id="cab_login_registrar">
        <div class="logoNome">
            <a href="">
                <img src="~/images/abacate-removebg-preview.png" alt="some text" width=50 height=51>
            </a>
            <a class="cabecalho__botao-nav" asp-action="Inicial" asp-controller="Home">MY CRITICS</a>
        </div>
        <a class="cabecalho__botao-nav" asp-controller="home" asp-action="Indicacoes">
            <p class="p"> Lista de Filmes </p>
        </a>
        <a class="cabecalho__botao-nav" asp-controller="Filmes" asp-action="Create">
            <p class="p"> Cadastrar Filme </p>
        </a>
        <div class="">
            <p></p>
            <a asp-controller="home" asp-action="Perfil">
                <img src="~/images/mulher-perfil.jpg" alt="some text" width=51 height=52 class="Pesquisa">
                <p class="Titulo"> @TempData.Peek("Nome") </p>
            </a>
            <p></p>
        </div>
    </div>
    <div class="Principal">

        <div class="Noticias">
            <a href="/">
                <center>
                    <img src="~/images/Corra.jpeg" alt="Corra!" title="Corra é sucesso de bilheteria!" width=1320 height=300 class="Pesquisa">
                </center>
            </a>
        </div>

        <div class="Conteudo">

            <div class="conteudo-left">
                <p class="Titulo"> Últimas avaliações dos amigos </p>
                <p class="avaliacoes">
                    <img src="~/images/Keanu.jpg" alt="some text" width=51 height=52 class="Pesquisa">Avaliou Matrix 4!
                </p>
                <p class="avaliacoes">
                    <img src="~/images/US.jpg" alt="some text" width=51 height=52 class="Pesquisa">Avaliou Spider-man 3!
                </p>
                <p class="avaliacoes">
                    <img src="~/images/Candyman.jpg" alt="some text" width=51 height=52 class="Pesquisa">Avaliou O Rei Macaco!
                </p>


            </div>



            <div class="mais-avaliados">

                <div class="titulo_conteudo_right">
                    <p class="Titulo"> Filmes mais avaliados </p>
                </div>
                <p></p>
                    <table>
                        <tbody>
                            @foreach (var item in Model) {
                                <tr>
                                    <td>
                                        <div class="dot">
                                            <p class="avaliacoes">@Html.DisplayFor(modelItem => item.Filme.Nome) </p>
                                            <p></p>
                                        </div>
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
            </div>

        </div>

    </div>


</body>

MyCritics/Views/Home/Perfil.cshtml
@model IEnumerable<MyCritics.Models.Avaliacao>
<body>
    <div class="cabecalho" id="cab_login_registrar">
        <div class="logoNome">
            <a href="">
                <img src="~/images/abacate-removebg-preview.png" alt="some text" width=50 height=51>
            </a>
            <a class="cabecalho__botao-nav" asp-action="Inicial" asp-controller="Home">MY CRITICS</a>
        </div>
        <a class="cabecalho__botao-nav" asp-controller="home" asp-action="Indicacoes">
            <p class="p"> Lista de Filmes </p>
        </a>
        <a class="cabecalho__botao-nav" asp-controller="Filmes" asp-action="Create">
            <p class="p"> Cadastrar Filme </p>
        </a>
        <div class="">
            <p></p>
            <a asp-controller="home" asp-action="Perfil">
                <img src="~/images/mulher-perfil.jpg" alt="some text" width=51 height=52 class="Pesquisa">
                <p class="Titulo"> @TempData.Peek("Nome") </p>
            </a>

            <p></p>
        </div>
    </div>
    <div class="Principal">
        <div class="capa">
            <img src="~/images/mulher-perfil.jpg" alt="some text" width=100% height=364>
        </div>
        <div class="conteudo">
            <div class="perfil-nome">
                <div class="dot">
                    <img src="~/images/mulher-perfil.jpg" alt="some text" width=158 height=158 class="foto">
                </div>
                <p>@TempData.Peek("Nome") @TempData.Peek("Sobrenome") </p>
            </div>
            <div class="perfil-nome">
                <p>Minhas Avaliações</p>
            </div>
            <div class="assistidos back-filmes-assistidos">
                <table class="table">
                    <thead>
                        <tr>
                            <th>
                                @Html.DisplayNameFor(model => model.Filme)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.NotaFilme)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.NotaDiretor)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.NotaFigurino)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.NotaRoteiro)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.NotaSonoplastia)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.Comentario)
                            </th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model) {
                            <tr>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Filme.Nome)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.NotaFilme)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.NotaDiretor)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.NotaFigurino)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.NotaRoteiro)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.NotaSonoplastia)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Comentario)
                                </td>
                                <td>
                                    <a asp-controller="Avaliacaos" asp-action="Edit" asp-route-id="@item.ID">Editar</a>
                                    <a asp-controller="Avaliacaos" asp-action="Delete" asp-route-id="@item.ID">Deletar</a>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</body>